name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: |
            Thanks for your first issue — you've officially opened a portal to this repository :-) Welcome aboard!
          pr-message: |
            Thanks for joining in! Movement is the path to perfection ;-)
